#pragma once

#include <stddef.h>

size_t host_strlcpy(char *destination, const char *source, size_t size);
#define strlcpy host_strlcpy

#define CONFIG_MOTION_PROFILE_LOW 0
#define CONFIG_MOTION_PROFILE_HIGH 0
#define CONFIG_MOTION_FEATURE_STANDARD_DEVIATION 0
#define CONFIG_MOTION_FEATURE_SAMPLE_VARIANCE 0
#define CONFIG_MOTION_FEATURE_RANGE 0
#define CONFIG_MOTION_FEATURE_MEDIAN_ABSOLUTE_DEVIATION 0
#define CONFIG_MOTION_BASELINE_MEDIAN_MAD 0
#define CONFIG_MOTION_WIFI_SSID ""
#define CONFIG_MOTION_WIFI_PASSWORD ""
#define CONFIG_MOTION_SAMPLE_INTERVAL_MS 100
#define CONFIG_MOTION_WINDOW_SIZE 20
#define CONFIG_MOTION_CALIBRATION_SAMPLES 120
#define CONFIG_MOTION_SIGMA_MULTIPLIER_X100 600
#define CONFIG_MOTION_MIN_THRESHOLD_X100 30
#define CONFIG_MOTION_RELEASE_THRESHOLD_RATIO_X100 75
#define CONFIG_MOTION_BASELINE_UPDATE_ALPHA_X10000 100
#define CONFIG_MOTION_TRIGGER_CONSECUTIVE 3
#define CONFIG_MOTION_CLEAR_CONSECUTIVE 8
